// <auto-generated />
using System;
using Konyhatunder_Szolgalat_Vizsgaremek.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_ASP.Migrations.VizsgaremekEtlap
{
    [DbContext(typeof(VizsgaremekEtlapContext))]
    [Migration("20260505151242_VizsgaremekEtlap")]
    partial class VizsgaremekEtlap
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FoodAllergen", b =>
                {
                    b.Property<ulong>("FoodId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("food_id");

                    b.Property<ushort>("AllergenId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("allergen_id");

                    b.HasKey("FoodId", "AllergenId");

                    b.HasIndex("AllergenId");

                    b.ToTable("food_allergens", (string)null);
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.Allergen", b =>
                {
                    b.Property<ushort>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("allergens", (string)null);
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.Category", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.DailyMenu", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateOnly>("MenuDate")
                        .HasColumnType("date")
                        .HasColumnName("menu_date");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.HasKey("Id");

                    b.ToTable("daily_menus", (string)null);
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.Food", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<uint>("CategoryId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("category_id");

                    b.Property<int?>("Kcal")
                        .HasColumnType("int")
                        .HasColumnName("kcal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("foods", (string)null);
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.Ingredient", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("base_unit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.Menu", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<uint>("PriceFt")
                        .HasColumnType("int unsigned")
                        .HasColumnName("price_ft");

                    b.HasKey("Id");

                    b.ToTable("menus", (string)null);
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.MenuAvailability", b =>
                {
                    b.Property<ulong>("DailyMenuId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("daily_menu_id");

                    b.Property<ulong>("MenuId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("menu_id");

                    b.Property<uint?>("MaxQty")
                        .HasColumnType("int unsigned")
                        .HasColumnName("max_qty");

                    b.HasKey("DailyMenuId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("menu_availability", (string)null);
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.MenuItem", b =>
                {
                    b.Property<ulong>("MenuId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("menu_id");

                    b.Property<ulong>("FoodId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("food_id");

                    b.Property<byte>("CourseOrder")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("course_order");

                    b.HasKey("MenuId", "FoodId");

                    b.HasIndex("FoodId");

                    b.ToTable("menu_items", (string)null);
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.Order", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("longtext")
                        .HasColumnName("comment");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("order_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.OrderItem", b =>
                {
                    b.Property<ulong>("OrderId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("order_id");

                    b.Property<ulong>("MenuId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("menu_id");

                    b.Property<uint>("Qty")
                        .HasColumnType("int unsigned")
                        .HasColumnName("qty");

                    b.Property<uint>("UnitPriceFt")
                        .HasColumnType("int unsigned")
                        .HasColumnName("unit_price_ft");

                    b.HasKey("OrderId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.RecipeItem", b =>
                {
                    b.Property<ulong>("FoodId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("food_id");

                    b.Property<ulong>("IngredientId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("ingredient_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("amount");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("unit");

                    b.HasKey("FoodId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("recipe_items", (string)null);
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.Role", b =>
                {
                    b.Property<ushort>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.Ticket", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<ushort>("TicketTypeId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("ticket_type_id");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TicketTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.TicketType", b =>
                {
                    b.Property<ushort>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ushort>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("ticket_types", (string)null);
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.UserRole", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.Property<ushort>("RoleId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("FoodAllergen", b =>
                {
                    b.HasOne("Konyhatunder_Szolgalat_Vizsgaremek.Models.Allergen", null)
                        .WithMany()
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Konyhatunder_Szolgalat_Vizsgaremek.Models.Food", null)
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.Food", b =>
                {
                    b.HasOne("Konyhatunder_Szolgalat_Vizsgaremek.Models.Category", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.MenuAvailability", b =>
                {
                    b.HasOne("Konyhatunder_Szolgalat_Vizsgaremek.Models.DailyMenu", "DailyMenu")
                        .WithMany("MenuAvailabilities")
                        .HasForeignKey("DailyMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Konyhatunder_Szolgalat_Vizsgaremek.Models.Menu", "Menu")
                        .WithMany("MenuAvailabilities")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyMenu");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.MenuItem", b =>
                {
                    b.HasOne("Konyhatunder_Szolgalat_Vizsgaremek.Models.Food", "Food")
                        .WithMany("MenuItems")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Konyhatunder_Szolgalat_Vizsgaremek.Models.Menu", "Menu")
                        .WithMany("MenuItems")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.Order", b =>
                {
                    b.HasOne("Konyhatunder_Szolgalat_Vizsgaremek.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.OrderItem", b =>
                {
                    b.HasOne("Konyhatunder_Szolgalat_Vizsgaremek.Models.Menu", "Menu")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Konyhatunder_Szolgalat_Vizsgaremek.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.RecipeItem", b =>
                {
                    b.HasOne("Konyhatunder_Szolgalat_Vizsgaremek.Models.Food", "Food")
                        .WithMany("RecipeItems")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Konyhatunder_Szolgalat_Vizsgaremek.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeItems")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.Ticket", b =>
                {
                    b.HasOne("Konyhatunder_Szolgalat_Vizsgaremek.Models.TicketType", "TicketType")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Konyhatunder_Szolgalat_Vizsgaremek.Models.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TicketType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.UserRole", b =>
                {
                    b.HasOne("Konyhatunder_Szolgalat_Vizsgaremek.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Konyhatunder_Szolgalat_Vizsgaremek.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.Category", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.DailyMenu", b =>
                {
                    b.Navigation("MenuAvailabilities");
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.Food", b =>
                {
                    b.Navigation("MenuItems");

                    b.Navigation("RecipeItems");
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeItems");
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.Menu", b =>
                {
                    b.Navigation("MenuAvailabilities");

                    b.Navigation("MenuItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.TicketType", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Konyhatunder_Szolgalat_Vizsgaremek.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Tickets");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
